server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hmdp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    host: 192.168.100.128
    port: 6379
    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  rabbitmq:
    host: 192.168.100.128
    port: 5672
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: 123 # 密码
    publisher-confirm-type: correlated # 开启发布确认
    publisher-returns: true # 开启发布返回
    template:
      mandatory: true # 消息路由失败时返回给生产者
    listener:
      simple:
        acknowledge-mode: auto # 自动确认，配合重试机制
        retry:
          enabled: true # 开启消费者失败重试
          initial-interval: 1000ms # 初始失败等待时长为1秒
          multiplier: 2 # 失败等待时长倍数
          max-attempts: 3 # 最大重试次数
          max-interval: 10000ms # 最大失败等待时长
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug
